spring.profiles.active: default
---
spring:
  jpa:
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  data.elasticsearch.properties:
    path.home: target/elastic
    transport.tcp.connect_timeout: 120s
endpoints:
  actuator:
    enabled: true
management:
  security:
    enabled: false  # disables security for Actuator endpoints, always change to true for PROD config
---
spring:
  profiles: docker
  data.jest.uri: http://localhost:9200
  datasource:  # Docker MySQL settings
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starbucks  # see docker-compose.yml for customizing db name, username & password
    username: starbucks_user
    password: ilikecoffee
---
spring:
  profiles: aws
  data.jest:
    uri: https://[AWS_ELASTICSEARCH_URI]  # URI for AWS Elasticsearch index
    aws-region: [AWS_REGION_NAME]
  datasource:  # RDS settings
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://[AWS_DB_HOST]:3306/starbucks
    username: [DB_USERNAME]
    password: [DB_PASSWORD]
---

